/*
 * TerminusDB API
 *
 * API for TerminusDB
 *
 * The version of the OpenAPI document: 10.0.3
 * Contact: team@terminusdb.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BranchPathPost200Response {
    #[serde(rename = "@type:", skip_serializing_if = "Option::is_none")]
    pub at_type_colon: Option<AtTypeColon>,
    #[serde(rename = "api:status", skip_serializing_if = "Option::is_none")]
    pub api_colon_status: Option<ApiColonStatus>,
}

impl BranchPathPost200Response {
    pub fn new() -> BranchPathPost200Response {
        BranchPathPost200Response {
            at_type_colon: None,
            api_colon_status: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AtTypeColon {
    #[serde(rename = "api:BranchResponse")]
    ApiColonBranchResponse,
}

impl Default for AtTypeColon {
    fn default() -> AtTypeColon {
        Self::ApiColonBranchResponse
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApiColonStatus {
    #[serde(rename = "api:success")]
    ApiColonSuccess,
}

impl Default for ApiColonStatus {
    fn default() -> ApiColonStatus {
        Self::ApiColonSuccess
    }
}

