/*
 * TerminusDB API
 *
 * API for TerminusDB
 *
 * The version of the OpenAPI document: 10.0.3
 * Contact: team@terminusdb.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DbOrganizationDatabasePutRequest {
    #[serde(rename = "comment")]
    pub comment: String,
    #[serde(rename = "label")]
    pub label: String,
    /// Should the database be accessible for all users?
    #[serde(rename = "public", skip_serializing_if = "Option::is_none")]
    pub public: Option<bool>,
    /// Should the database be initialized with a schema?
    #[serde(rename = "schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<bool>,
}

impl DbOrganizationDatabasePutRequest {
    pub fn new(comment: String, label: String) -> DbOrganizationDatabasePutRequest {
        DbOrganizationDatabasePutRequest {
            comment,
            label,
            public: None,
            schema: None,
        }
    }
}


