/*
 * TerminusDB API
 *
 * API for TerminusDB
 *
 * The version of the OpenAPI document: 10.0.3
 * Contact: team@terminusdb.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DbOrganizationDatabasePost400ResponseApiError {
    #[serde(rename = "@type", skip_serializing_if = "Option::is_none")]
    pub at_type: Option<String>,
    #[serde(rename = "api:database_name", skip_serializing_if = "Option::is_none")]
    pub api_colon_database_name: Option<String>,
    #[serde(rename = "api:organization_name", skip_serializing_if = "Option::is_none")]
    pub api_colon_organization_name: Option<String>,
}

impl DbOrganizationDatabasePost400ResponseApiError {
    pub fn new() -> DbOrganizationDatabasePost400ResponseApiError {
        DbOrganizationDatabasePost400ResponseApiError {
            at_type: None,
            api_colon_database_name: None,
            api_colon_organization_name: None,
        }
    }
}


