/*
 * TerminusDB API
 *
 * API for TerminusDB
 *
 * The version of the OpenAPI document: 10.0.3
 * Contact: team@terminusdb.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiffPostRequest {
    #[serde(rename = "before", skip_serializing_if = "Option::is_none")]
    pub before: Option<serde_json::Value>,
    #[serde(rename = "after", skip_serializing_if = "Option::is_none")]
    pub after: Option<serde_json::Value>,
    #[serde(rename = "keep", skip_serializing_if = "Option::is_none")]
    pub keep: Option<serde_json::Value>,
}

impl DiffPostRequest {
    pub fn new() -> DiffPostRequest {
        DiffPostRequest {
            before: None,
            after: None,
            keep: None,
        }
    }
}


