/*
 * TerminusDB API
 *
 * API for TerminusDB
 *
 * The version of the OpenAPI document: 10.0.3
 * Contact: team@terminusdb.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InfoGet200ResponseApiInfoTerminusdbStore {
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl InfoGet200ResponseApiInfoTerminusdbStore {
    pub fn new() -> InfoGet200ResponseApiInfoTerminusdbStore {
        InfoGet200ResponseApiInfoTerminusdbStore {
            version: None,
        }
    }
}


