/*
 * TerminusDB API
 *
 * API for TerminusDB
 *
 * The version of the OpenAPI document: 10.0.3
 * Contact: team@terminusdb.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InfoGet200ResponseApiInfo {
    #[serde(rename = "authority", skip_serializing_if = "Option::is_none")]
    pub authority: Option<String>,
    #[serde(rename = "storage", skip_serializing_if = "Option::is_none")]
    pub storage: Option<Box<crate::models::InfoGet200ResponseApiInfoStorage>>,
    #[serde(rename = "terminusdb", skip_serializing_if = "Option::is_none")]
    pub terminusdb: Option<Box<crate::models::InfoGet200ResponseApiInfoTerminusdb>>,
    #[serde(rename = "terminusdb_store", skip_serializing_if = "Option::is_none")]
    pub terminusdb_store: Option<Box<crate::models::InfoGet200ResponseApiInfoTerminusdbStore>>,
}

impl InfoGet200ResponseApiInfo {
    pub fn new() -> InfoGet200ResponseApiInfo {
        InfoGet200ResponseApiInfo {
            authority: None,
            storage: None,
            terminusdb: None,
            terminusdb_store: None,
        }
    }
}


