/*
 * TerminusDB API
 *
 * API for TerminusDB
 *
 * The version of the OpenAPI document: 10.0.3
 * Contact: team@terminusdb.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchPostRequest {
    #[serde(rename = "before", skip_serializing_if = "Option::is_none")]
    pub before: Option<serde_json::Value>,
    #[serde(rename = "patch", skip_serializing_if = "Option::is_none")]
    pub patch: Option<serde_json::Value>,
}

impl PatchPostRequest {
    pub fn new() -> PatchPostRequest {
        PatchPostRequest {
            before: None,
            patch: None,
        }
    }
}


