/*
 * TerminusDB API
 *
 * API for TerminusDB
 *
 * The version of the OpenAPI document: 10.0.3
 * Contact: team@terminusdb.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullPathPostRequest {
    /// The name of the remote to push to
    #[serde(rename = "remote")]
    pub remote: String,
    /// The name of the branch on the remote to push
    #[serde(rename = "remote_branch")]
    pub remote_branch: String,
}

impl PullPathPostRequest {
    pub fn new(remote: String, remote_branch: String) -> PullPathPostRequest {
        PullPathPostRequest {
            remote,
            remote_branch,
        }
    }
}


