/*
 * TerminusDB API
 *
 * API for TerminusDB
 *
 * The version of the OpenAPI document: 10.0.3
 * Contact: team@terminusdb.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PushPathPostRequest {
    /// The name of the remote to push to
    #[serde(rename = "remote")]
    pub remote: String,
    /// The name of the branch on the remote to push
    #[serde(rename = "remote_branch")]
    pub remote_branch: String,
    /// Should the prefixes also be pushed to the remote?
    #[serde(rename = "push_prefixes", skip_serializing_if = "Option::is_none")]
    pub push_prefixes: Option<bool>,
}

impl PushPathPostRequest {
    pub fn new(remote: String, remote_branch: String) -> PushPathPostRequest {
        PushPathPostRequest {
            remote,
            remote_branch,
            push_prefixes: None,
        }
    }
}


