/*
 * TerminusDB API
 *
 * API for TerminusDB
 *
 * The version of the OpenAPI document: 10.0.3
 * Contact: team@terminusdb.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PushPathPost400Response {
    #[serde(rename = "@type", skip_serializing_if = "Option::is_none")]
    pub at_type: Option<AtType>,
    #[serde(rename = "api:error", skip_serializing_if = "Option::is_none")]
    pub api_colon_error: Option<serde_json::Value>,
    #[serde(rename = "api:message", skip_serializing_if = "Option::is_none")]
    pub api_colon_message: Option<String>,
    #[serde(rename = "api:status", skip_serializing_if = "Option::is_none")]
    pub api_colon_status: Option<ApiColonStatus>,
}

impl PushPathPost400Response {
    pub fn new() -> PushPathPost400Response {
        PushPathPost400Response {
            at_type: None,
            api_colon_error: None,
            api_colon_message: None,
            api_colon_status: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AtType {
    #[serde(rename = "api:PushErrorResponse")]
    ApiColonPushErrorResponse,
}

impl Default for AtType {
    fn default() -> AtType {
        Self::ApiColonPushErrorResponse
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApiColonStatus {
    #[serde(rename = "api:failure")]
    ApiColonFailure,
}

impl Default for ApiColonStatus {
    fn default() -> ApiColonStatus {
        Self::ApiColonFailure
    }
}

