/*
 * TerminusDB API
 *
 * API for TerminusDB
 *
 * The version of the OpenAPI document: 10.0.3
 * Contact: team@terminusdb.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResetPathPostRequest {
    #[serde(rename = "commit_descriptor", skip_serializing_if = "Option::is_none")]
    pub commit_descriptor: Option<String>,
}

impl ResetPathPostRequest {
    pub fn new() -> ResetPathPostRequest {
        ResetPathPostRequest {
            commit_descriptor: None,
        }
    }
}


